tmpfolder: "/tmp/gobserver/"
appport: ":8081"
db:
  dbname: "gobserver"
  dbtype: "postgres"
  dbuser: "gobuser"
  dbpass: "gobpass"
  dbhost: "127.0.0.1"
  dbport: "5432"
  dbssl: "disable"
  dbtimezone: "UTC"
log:
  logpath: "/tmp/gobserver/logs"
  loglevel: "debug"
  logtruncate: true
